### ISSUE TITLE
A question of function GetTotalAABB()

### ISSUE THREAD

**Issue by olivertai** [projectchrono/chrono#120]
Hello, I have successfully built a physical system using module parallel, but then I found out a problem with the function GetTotalAABB(), details are as follows:
When I define the system like:
`
ChSystemNSC mphysicalSystem(false,1000,20);
auto scene = std::make_shared<ChBody>();
scene->SetPos(ChVector<>(0, 0, 0));
scene->SetBodyFixed(true);
mphysicalSystem.Add(scene);
scene->GetCollisionModel()->ClearModel();
scene->GetCollisionModel()->AddTriangleMesh(mmeshbox,false, false, VNULL, ChMatrix33<>(1), 0.005);
scene->GetCollisionModel()->BuildModel();
scene->SetCollide(true);
ChVector<> bbmin, bbmax;
scene->GetTotalAABB(bbmin,bbmax);
std::cout<<"min of scene"<<bbmin.x()<<" "<<bbmin.y()<<" "<<bbmin.z()<<" "<<std::endl;
std::cout<<"max of scene"<<bbmax.x()<<" "<<bbmax.y()<<" "<<bbmax.z()<<" "<<std::endl;
`
I get outputs like:
`
min of scene-0.587664 -0.0730529 -8.3998 
max of scene5.23018 4.38043 4.31234 
`
Then I just changed several lines to use module parallel:
`
ChSystemParallelNSC mphysicalSystem;
auto scene = std::make_shared<ChBody>(std::make_shared<collision::ChCollisionModelParallel>());
ChVector<> bbmin, bbmax;
scene->GetTotalAABB(bbmin,bbmax);
std::cout<<"min of scene"<<bbmin.x()<<" "<<bbmin.y()<<" "<<bbmin.z()<<" "<<std::endl;
std::cout<<"max of scene"<<bbmax.x()<<" "<<bbmax.y()<<" "<<bbmax.z()<<" "<<std::endl;
`
I didn't change other things and I got:
`
min of scene0 0 0 
max of scene0 0 0 
`
Is there  something I was missing or I just misunderstood this function? Thank you.

**Comment by rserban** [comment]
Could you please post this type of questions on the user mailing list?  This has more to do with Chrono usage, rather than issues or feature requests.  Thanks!
