### ISSUE TITLE
Compiler error C1128 when building with Visual Studio 2015

### ISSUE THREAD

**Issue by kyberias** [projectchrono/chrono#121]
Followed the instructions here: http://api.projectchrono.org/tutorial_install_chrono.html

chrono\src\chrono\utils\ChParserOpenSim.cpp : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj

64-bit Debug build.

**Comment by rserban** [comment]
I pushed a fix for this. 
I assume you are using Visual Studio 2015 (as this issue does not occur with Visual Studio 2017), correct?
Please let me know if the fix works for you.
--Radu

**Comment by kyberias** [comment]
I think it fixed it. Thank you very much. This was indeed VS 2015.
