### ISSUE TITLE
Documentations are not working 

### ISSUE THREAD

**Issue by saleh9292** [projectchrono/chrono#141]
sorry for the re-post as I have already posted this in the forums. but I am not sure if it was the right place.

the documentation at http://api.projectchrono.org/development/   seems to be broken,
is there any alternatives?

**Comment by rserban** [comment]
I already replied to you on the mailing list: we are having some doxygen-related issues, but we're working on fixing this.
In the meantime, look at the Chrono 3.0 documentation. With some exceptions, it is mostly valid for the current development version.

**Comment by saleh9292** [comment]
thank you for your quick reply :)

**Comment by conlain-k** [comment]
Hello @saleh9292, the issue should be fixed now.

**Comment by saleh9292** [comment]
yes, i can confirm it. thanks.
