### ISSUE TITLE
error: use of overloaded operator '[]' is ambiguous (with operand types 'chrono::quaternion' and 'int')

### ISSUE THREAD

**Issue by yurivict** [projectchrono/chrono#154]
Build of 4.0.0-89-ge36b5a9ce on FreeBSD  12 i386 fails:
```
/wrkdirs/usr/ports/science/chrono/work/chrono-4.0.0-89-ge36b5a9ce/src/chrono_parallel/math/real4.cpp:160:9: error: use of overloaded operator '[]' is ambiguous (with operand types 'chrono::quaternion' and 'int')
    quat[0] = axis[0] * sinhalf;
    ~~~~^~
```

See the full log here: http://beefy5.nyi.freebsd.org/data/120i386-default/500946/logs/chrono-4.0.0.89.log

**Comment by thepianoboy** [comment]
Chrono does not actively support 32-bit architectures. If you are able to reproduce this issue on FreeBSD 12 amd64, feel free to post and reference #157.
