### ISSUE TITLE
ChQuaternion<Real>::GetInverse() const not correct

### ISSUE THREAD

**Issue by martijnpot52** [projectchrono/chrono#180]
We tested the Quaternion inverse (`ChQuaternion<Real>::GetInverse() const`) in a google test:
```
TEST(Quaternion, Inverse) {
    chrono::Quaternion q{-0.5, 2.0, 1.5, 0.1};
    chrono::Quaternion qinv = q.GetInverse();
    chrono::Quaternion qmult = q % qinv;

    chrono::Quaternion qident{1.0, 0.0, 0.0, 0.0};

    NEAR(qmult, qident, toleranceConstant, std::to_string(__LINE__));
}
```

This test fails:
_The difference between q1.e0() and q2.e0() is 1.5514701644346149, which exceeds tolerance, where
q1.e0() evaluates to 2.5514701644346149,
q2.e0() evaluates to 1, and
tolerance evaluates to 9.9999999999999995e-07._

The problem is that the conjugate is only divided by Length() whereas it should be divided by Length2() (see e.g. at equation 14 of the Project Chrono rotations white paper).

Changed code:
```
template <class Real>
inline ChQuaternion<Real> ChQuaternion<Real>::GetInverse() const {
    ChQuaternion<Real> invq = this->GetConjugate();
    invq.Scale(1 / this->Length2());
    return invq;
}
```

The test passed with this change.

**Comment by rserban** [comment]
Hi Martin,
You are correct, that appears to be a bug (no impact on the rest of the code as far as I can tell).
I will push the fix soon.
Thanks you for reporting this.
--Radu
