### ISSUE TITLE
PyChrono - failed to run demo_irrlicht.py

### ISSUE THREAD

**Issue by ZhiquanW** [projectchrono/chrono#185]
I installed PyChrono-4.0.0 from Anaconda. OS is ubuntu18.04lts.
It seems irrlicht is not installed correctly
![image](https://user-images.githubusercontent.com/22308667/64902789-c40cb780-d67b-11e9-9db3-26cf7753c849.png)
.

**Comment by Benatti1991** [comment]
It looks like Irrlicht itself is not installed.
On your shell, run this command:
`sudo apt-get install libirrlicht-dev`

**Comment by ZhiquanW** [comment]
Thank you for your help. This issue is solved according to your instruction.
