### ISSUE TITLE
Update Camera Position in Irrlicht

### ISSUE THREAD

**Issue by ZhiquanW** [projectchrono/chrono#196]
Is there any way to update the position of the camera per frame when simulate with irrlicht?

**Comment by rserban** [comment]
Simply access the current camera from the ChIrrApp and then set its position and target:
```
auto camera = application.GetSceneManager()->getActiveCamera();
camera->setPosition(new_position);
camera->setTarget(new_target);
```
See for example demo_VEH_TireTestRig.cpp

**Comment by ZhiquanW** [comment]
Thank you! Sometimes, It's hard to find those examples of specific functions from the demos.
