### ISSUE TITLE
FSI module boundary conditions

### ISSUE THREAD

**Issue by joeelrahi** [projectchrono/chrono#209]
Hello,

I wish to couple the FSI module with a wave propagation model, in order to study wave attenuation due to fluid-solid interaction.
 According to my understanding, the FSI simulation parameters are set through the *.json file. 

Would it be possible to force the FSI module with boundary velocities ( several layers/time series) ?

Thank you for expanding on this matter,
regards,
Joe

**Comment by rserban** [comment]
Joe, I suggest posting questions such as this on the user forum (http://projectchrono.org/forum/).  More people see the messages posted there than follow the GitHub issues.
