### ISSUE TITLE
vehicle project setup  guide

### ISSUE THREAD

**Issue by yumianhuli2** [projectchrono/chrono#211]
1、I found that https://github.com/projectchrono/chrono-tutorial, and I clone it into demos/vehicle folder named it demo_sampleCar.Then I add ADD_SUBDIRECTORY(demo_sampleCar) in cmakeList.txt.
So My question is where can I find the switch of enable compile vehicle module?
2、How many degrees of freedom does the chrono car have？
3、One car can be run in a high performance pc？
4、how can I get ray(contact with slope ground situation)vector and origin point from chrono?
Thank you very much!

**Comment by rserban** [comment]
See the installation instructions at http://api.projectchrono.org/development/tutorial_table_of_content_install.html
and how optional modules (including the vehicle module) are enabled during CMake configuration.

Once you enable both the Irrlicht and Vehicle modules, you will get many more demos, including several for various vehicle simulations using various different vehicle models.   I recommend starting with those.

The projects in the chrono-tutorial repository are set up as "external" projects using the Chrono libraries.  To see how to build such projects, see http://api.projectchrono.org/development/tutorial_install_project.html 

Various vehicle models have different numbers of DOFs.

I assume you ask about whether or not a single vehicle will run in (soft) real-time on a performant machine.  The answer is yes, it should.

Ray casting can be done using the underlying collision detection library.  This is an advanced topic, but look at the ChCollisionSystem::RayHit function in the API documentation.

**Comment by yumianhuli2** [comment]
> See the installation instructions at http://api.projectchrono.org/development/tutorial_table_of_content_install.html
> and how optional modules (including the vehicle module) are enabled during CMake configuration.
> 
> Once you enable both the Irrlicht and Vehicle modules, you will get many more demos, including several for various vehicle simulations using various different vehicle models. I recommend starting with those.
> 
> The projects in the chrono-tutorial repository are set up as "external" projects using the Chrono libraries. To see how to build such projects, see http://api.projectchrono.org/development/tutorial_install_project.html
> 
> Various vehicle models have different numbers of DOFs.
> 
> I assume you ask about whether or not a single vehicle will run in (soft) real-time on a performant machine. The answer is yes, it should.
> 
> Ray casting can be done using the underlying collision detection library. This is an advanced topic, but look at the ChCollisionSystem::RayHit function in the API documentation.

Hello! I installed IRRLICHT1.8.4 and cmake-gui.But I got below:
![Screenshot from 2020-01-07 15-09-04](https://user-images.githubusercontent.com/39210837/71875600-a948dc00-315f-11ea-80dc-295bb86f03eb.png)
![Screenshot from 2020-01-07 15-10-35](https://user-images.githubusercontent.com/39210837/71875738-fe84ed80-315f-11ea-8c65-7242e6d43183.png)
![Screenshot from 2020-01-07 15-11-07](https://user-images.githubusercontent.com/39210837/71875741-00e74780-3160-11ea-9bb3-5c5b1a348202.png)

**Comment by rserban** [comment]
This is likely due to the fact that you copied that demo from the chrono-tutorial repository into your Chrono clone.    As I've already told you, projects such as those in 'chrono-tutorial' are built differently (see the link I provided).

Simply clean up your Chrono clone, clean the cmake cache, and reconfigure.

You should not see a variable 'Chrono_DIR' when configuring Chrono.
