### ISSUE TITLE
compile my_example.cpp on ubuntu16.04

### ISSUE THREAD

**Issue by yumianhuli2** [projectchrono/chrono#212]
Hello!(issues on ubuntu16.04)
I added add_subdirectory(template_project) in root cmakeList
![Screenshot from 2020-01-07 16-16-41](https://user-images.githubusercontent.com/39210837/71879467-1f9e0c00-3169-11ea-85e4-bef7f1a7194d.png)
and I found this below:
![Screenshot from 2020-01-07 16-22-31](https://user-images.githubusercontent.com/39210837/71879817-eade8480-3169-11ea-9c23-ee02aacceae1.png)
But I can not find myexe anywhere ?

When I run cmake &&make I just found these programs
![Screenshot from 2020-01-07 16-28-15](https://user-images.githubusercontent.com/39210837/71880231-cf27ae00-316a-11ea-8df9-1aee4c0716d2.png)

plz help me run the project such as my_example.cpp/myexe ,Thank U!

**Comment by rserban** [comment]
This is not how any of this works.  Please read carefully the documentation at http://api.projectchrono.org/development/index.html and take this one step at a time.
