### ISSUE TITLE
Particles flowing out of Boundary - Dam Break

### ISSUE THREAD

**Issue by joeelrahi** [projectchrono/chrono#213]
![out_of_boundary_LI](https://user-images.githubusercontent.com/49030919/71913081-f2f0f100-3176-11ea-9655-9a4b2f0e4bfe.jpg)

Hello! I'm testing the SPH solver and I sometimes encounter odd outputs. In this snapshot few particles flow out of the boundary. Is this related to some inherited bug? Should I ignore it and carry on? else do you have any suggestions.

thanks in advance,
Joe

**Comment by Milad-Rakhsha** [comment]
It is likely that this is related to the choice of parameters in your simulation and not a bug; most likely the choice of the time-step.
I think a better place to post these kinds of problems is the Chrono forums, where other users can learn from such conversations. Here is a link:
https://projectchrono.org/forum/
