### ISSUE TITLE
conda-forge pypy support

### ISSUE THREAD

**Issue by davidbrochart** [projectchrono/chrono#230]
There is an effort in conda-forge which consists of supporting PyPy for all current CPython packages. The migration is ongoing, and for pychrono we have an error (full log [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=141708&view=logs&jobId=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=113b264d-9551-5065-da10-7eb3bdeaf1bc)):
```
/usr/local/miniconda/conda-bld/chrono_1586361813812/work/src/chrono_python/ChPython.cpp:38:2: error: use of undeclared identifier 'Py_Initialize'
        Py_Initialize();
        ^
/usr/local/miniconda/conda-bld/chrono_1586361813812/work/src/chrono_python/ChPython.cpp:43:2: error: use of undeclared identifier 'Py_Finalize'
        Py_Finalize()
```
I know that you use swig for the Python bindings, and it might not work for PyPy. Is there a plan to do the bindings differently (https://cffi.readthedocs.io, https://pybind11.readthedocs.io)?

**Comment by rserban** [comment]
There is no plan to switch to CFFI or pybind11.  We do not have the bandwidth, nor the funding to engage in such a project.

Despite its shortcomings, SWIG has one advantage: it also supports other languages. In particular, I am considering using it with C# to allow accessing the Chrono functionality through the PInvoke interface.  I expect (hope) we can reuse much of the existing SWIG code we already have.
