### ISSUE TITLE
Mismatch between template_project and Chrono 5.x

### ISSUE THREAD

**Issue by BoringNickname** [projectchrono/chrono#242]
Hi,

I'm very new to Chrono engine. Everything went well when compiling the source code.
But after I built the default template_project, there were no bodies shown in the scene (just the scene is displayed).
I checked the documentation and found the `chrono::ChBodyEasyBox Class` parameters are different between 4.x and 5.x.
The 5th and 6th parameters `bool visualize=true` and `bool collide=false` are swapped but the template is not updated.

[http://api.projectchrono.org/classchrono_1_1_ch_body_easy_box.html#a61731166b28e8dea817b941bf41be6ab](url)
[http://api.projectchrono.org/4.0.0/classchrono_1_1_ch_body_easy_box.html#ad321df24d087b1d8f138a498f01dc04b](url)

Hope this could be fixed. Beginners would get confused when template has errors.

Thanks a lot.

**Comment by rserban** [comment]
Thanks for pointing this out.  I missed updating this example when making the changes that included the ChBodyEasy API changes.   This was fixed and pushed to the repository.

Just to clarify: this was an issue only in the current development code (those changes I mentioned above happened after the 5.0 release and the sample code there matches the API in the release code)
