### ISSUE TITLE
ChronoConfig.cmake file from Windows binary installer has hard coded username

### ISSUE THREAD

**Issue by rpherman** [projectchrono/chrono#248]
I installed Chrono via the Windows binary installer on the project site because of issues building Chrono. When I try setting up the template project, I get a warning and find there is a hard-coded username in the ProjectChrono/cmake/ChronoConfig.cmake file ("cvandenheuve") that causes my generated VS solution to fail. I could go in and manually change them, but shouldn't this be an environment variable reference?

```
if (${CMAKE_SYSTEM_NAME} MATCHES "Windows")
  set(CHRONO_LINKER_FLAGS "")
else()
  set(CHRONO_LINKER_FLAGS "-LC:/Users/cvandenheuve/Documents/prefix/lib")
endif()
```

**Comment by thepianoboy** [comment]
This bug should be fixed with the latest binary release candidate.
