### ISSUE TITLE
 Irrlicht1.8.4 install

### ISSUE THREAD

**Issue by yumianhuli2** [projectchrono/chrono#262]
Hello Chrono Team and Dear @rserban @yurivict @storrgie @aluaces @bartoszek @andrewseidl :)!
I have  installed the Irrlicht1.8.4 engine and run examples of irrlicht1.8.4 successfully on Ubuntu16.04.
The steps  to install Irrlicht1.8.4 are as follows：
1、cd ./source/Irrlicht 
2、make
3、sudo cp -r include/* /usr/local/include/
4、sudo cp lib/Linux/libIrrlicht.a /usr/local/lib
5、 sudo ./buildAllExamples.sh

And then I used: 
1 cmake  -DENABLE_MODULE_IRRLICHT=TRUE -DENABLE_MODULE_VEHICLE=TRUE ..
2 make -j8
But got error below:
![Screenshot from 2020-08-29 23-08-41](https://user-images.githubusercontent.com/39210837/91639921-9c5d5d80-ea4c-11ea-99ac-0f2fe56f954f.png)

Obviously, something wrong happened in the process of Irrlicht1.8.4 installation. What are the correct steps in this process?
Thanks！

**Comment by aluaces** [comment]
Hi, I think you have to install the GLUT developer libraries:

    sudo apt-get install freeglut3-dev

**Comment by yumianhuli2** [comment]
> Hi, I think you have to install the GLUT developer libraries:
> 
> ```
> sudo apt-get install freeglut3-dev
> ```

Very help! Chrono works!
By the way, why are the vehicles in Chrono's vehicle demo running so slowly? Is there a  real-time demo?
Thank you very much!

**Comment by Benatti1991** [comment]
They really shouldn't, are you building in Debug or Release?

**Comment by yumianhuli2** [comment]
> They really shouldn't, are you building in Debug or Release?

Successfully compiled
