### ISSUE TITLE
unit_CASCADE does not support OpenCASCADE 6.8

### ISSUE THREAD

**Issue by andrewseidl** [projectchrono/chrono#27]
It appears that OpenCASCADE 6.8 has changed or removed `BRepMesh::Mesh`, which is used by `unit_CASCADE/ChCascadeMeshTools.cpp` and `unit_CASCADE/ChIrrCascadeMeshTools.h`. This prevents the use of Chrono with the latest versions of OpenCASCADE.

**Comment by tasora** [comment]
Fixed. Open Cascade supported up to 6.9
