### ISSUE TITLE
Q_from_Vect_to_Vect() returns an incorrect result

### ISSUE THREAD

**Issue by Boring-Name** [projectchrono/chrono#279]
Hi,

I used the function `Q_from_Vect_to_Vect()` to get some rotation information but found it returned wrong reults.

Inside its definition, it seems that the axis parts `e1`, `e2`, `e3` should be multiplied by the varialbe `sinhalf` but not actually.
And the `ChAtan2()` function is passed with `sinangle` and then `cosangle` values but the definition of `ChAtan2()` uses a reversed order of them.
I tested amending these two places and it works well for me.

File path: "src/chrono/core/ChQuaternion.cpp".

Hope this information helps.

Thanks a lot.

**Comment by tasora** [comment]
Hi,

I fixed the bug, thank you for reporting. I will push it to GIT in next 
half hour.

Alessandro Tasora
