### ISSUE TITLE
Will the version of the ChronoEngine package in the Arch software repository be updated to 6.0?

### ISSUE THREAD

**Issue by hunter1992** [projectchrono/chrono#314]
Hello, developers of Project Chrono! 
Show respect for your efforts! 
Will the version of the ChronoEngine package in the Arch software repository be updated to 6.0?
Looking forward to an exciting update, salute again!

**Comment by rserban** [comment]
We are not the maintainers of the arch package.  You'll need to contact them about updating to v 6.0.
--Radu

**Comment by alhirzel** [comment]
It appears to be updated here in the AUR as of June: https://aur.archlinux.org/packages/chronoengine/
