### ISSUE TITLE
Stop enforcing ccache usage?

### ISSUE THREAD

**Issue by mablanchard** [projectchrono/chrono#324]
It seems like Chrono's CMake scripts [enforce `ccache` usage if detected](https://github.com/projectchrono/chrono/blob/develop/CMakeLists.txt#L90:L95). This isn't as great as it sound, I think, as it locks the caller into using something he hasn't asked for and that he is not able to deactivate.

Also, starting with CMake 3.4 (Chrono requires 3.10), one can [add `-DCMAKE_CXX_COMPILER_LAUNCHER=ccache`](https://cmake.org/cmake/help/latest/prop_tgt/LANG_COMPILER_LAUNCHER.html) to their configure command line in order to activate `ccache` or other tool support.

I'd be in favor of simply dropping that support. Comments?

**Comment by thepianoboy** [comment]
Implemented in f782572a348c9fc5bf2d9455d77d9b23599d28ac
