### ISSUE TITLE
Getting swig erro with version 3.0.12

### ISSUE THREAD

**Issue by akhil22** [projectchrono/chrono#326]
I tried using pychrono by both building the c++ module by source (master branch) and using anaconda. 

After installing I get this swig error when I run  demo_CH_buildsystem.py:
SWIG director method error. Error detected when calling 'ReportContactCallback.OnReportContact

The swig version used by both is 3.0.12 (I can see this version in ccmake gui as being set properly) Which is the version required by chrono 6.0.0.
Also the anaconda version of pychrono that is being installed is 6.0.0.

Is there something wrong with the dependencies ? Currently I am using the master branch to build pychrono, should I change it to some other branch ?

System information:
OS: Ubuntu 18.04

**Comment by rserban** [comment]
The information on the ProjectChrono installation webpage for Chrono::Python is out of date.  Sorry about that...
You should use SWIG 4.0 or newer.  I will push a fix to the documentation shortly.
