### ISSUE TITLE
Possible typo: Eulero

### ISSUE THREAD

**Issue by alhirzel** [projectchrono/chrono#332]
Is Euler meant instead of Eulero?

https://github.com/projectchrono/chrono/search?q=Eulero

Example:

https://github.com/projectchrono/chrono/blob/03931da6b00cf276fc1c4882f43b2fd8b3c6fa7e/src/chrono/core/ChMatrix33.h#L378

**Comment by tasora** [comment]
Yes, this is the same. The reason is that this was an old part of the 
code, where I used the italian spelling for Euler, that is Eulero.

Alessandro
