### ISSUE TITLE
demo issues with texture

### ISSUE THREAD

**Issue by huisky2000** [projectchrono/chrono#341]
Hi,
The project has been successfully compiled, however the demo example 'demo_IRR_collision_trimesh.exe' ended up with following errors:

Copyright (c) 2017 projectchrono.org
Chrono version: 6.0.0

Irrlicht Engine version 1.8.4
 (Build 9200)
Using renderer: Direct3D 9.0
Intel(R) UHD Graphics igdumdim64.dll 27.20.100.8853
Currently available Video Memory (kB): 4187136
Could not load shader function D3DXAssembleShader from dll, shaders disabled: d3dx9_43.dll
Could not create vertex shader.
Could not create vertex shader.
Resizing window (1280 720)
Resetting D3D9 device.
Could not load shader function D3DXCompileShader from dll, shaders disabled: d3dx9_43.dll
Loaded texture: C:/Arbeid/Softs/Chrono/chrono-build/bin/data/fonts/arial80.bmp
PNG warning: iCCP: known incorrect sRGB profile
Loaded texture: C:/Arbeid/Softs/Chrono/chrono-build/bin/data/logo_chronoengine_alpha.png
Loaded texture: C:/Arbeid/Softs/Chrono/chrono-build/bin/data/skybox/sky_lf.jpg
Loaded texture: C:/Arbeid/Softs/Chrono/chrono-build/bin/data/skybox/sky_dn.jpg
Loaded texture: C:/Arbeid/Softs/Chrono/chrono-build/bin/data/skybox/sky_up.jpg
Loaded texture: C:/Arbeid/Softs/Chrono/chrono-build/bin/data/textures/concrete.jpg
Could not open file of texture: XEFFECTS_SM_512
XEffects: Please ignore previous warning, it is harmless.
Could not open file of texture: XEFFECTS_SM_512_2
XEffects: Please ignore previous warning, it is harmless.

Does anybody know why?

**Comment by rserban** [comment]
Try updating your DirectX and video drivers

**Comment by rserban** [comment]
No, that should be enough.  Could you please post here your CMakeCache.txt file?
