### ISSUE TITLE
CMake: Cannot be built as a subdirectory via FetchContent or a git submodule

### ISSUE THREAD

**Issue by seanmiddleditch** [projectchrono/chrono#346]
Chrono cannot be built as a regular library cleanly by just `add_subdirectory` on the source directory.

This defeats the ability to use Chrono as a git submodule, or to build it as a dependency via CMake's builtin `FetchContent` functionality, which is increasingly common and idiosyncratic in the CMake world.

These use cases also generally _just_ want the core libraries, not any demos, benchmarks, tests, etc. Non-top-level projects should also avoid setting global properties or CMake configuration that would override or interfere with the top-level project's desired configuration.

**Comment by thepianoboy** [comment]
Seeing as the initial respondent has not provided any more information, I'm going to close this as a stale issue.

I think I've flagged a number of the settings that would impact this capability (for other reasons), and they are on my list of things to work on, so perhaps they'll end up resolved anyway.
