### ISSUE TITLE
"demo_POST_povray" crashes

### ISSUE THREAD

**Issue by Boring-Name** [projectchrono/chrono#351]
Dear developers,

Recently I tried to generate pov-ray files from the simulation instead of irrlicht visualisation. But when I run the "demo_POST_povray" it will crash with error message "Segmentation fault (core dumped)".

I found that the code caused this problem are the lines 129-133, as follows:

    // ==Asset== Attach, in this level, a 'Wavefront mesh' asset,
    // referencing a .obj file:
    auto mobjmesh = chrono_types::make_shared<ChObjShapeFile>();
    mobjmesh->SetFilename(GetChronoDataFile("models/forklift/body.obj"));
    mlevelA->AddAsset(mobjmesh);

Remove this "mobjmesh" will make the program run smoothly but I don't know the reason caused it.

Hope it helps.

Thanks.

**Comment by rserban** [comment]
There is indeed a bug in the povray code. I will push a fix shortly.
