### ISSUE TITLE
tutorial_demo_powertrain.html uses the header chrono/physics/ChShaftsFreewheel.h that is not installed by 7.0.1

### ISSUE THREAD

**Issue by yurivict** [projectchrono/chrono#361]
[Here](https://api.projectchrono.org/tutorial_demo_powertrain.html).

**Comment by rserban** [comment]
You are looking at the Chrono documentation for the **_develop_** branch.  `ChShaftsFreewheel` was added after the 7.0 release.
The documentation for the 7.0 release is at https://api.projectchrono.org/7.0.0 for which the particular page you mention is https://api.projectchrono.org/7.0.0/tutorial_demo_powertrain.html.  The listing on that page does not use the header `ChShaftsFrewheel.h`.
