### ISSUE TITLE
make template projects as separate git repositories and link them as submodules

### ISSUE THREAD

**Issue by IvanVnucec** [projectchrono/chrono#376]
Make
[template_project](https://github.com/projectchrono/chrono/tree/develop/template_project) and
[template_project_vehicle_cosim](https://github.com/projectchrono/chrono/tree/develop/template_project_vehicle_cosim)
as git submodules because it is unwise to clone whole Chrono repo in order to get only the template projects dirs.

**Comment by rserban** [comment]
These are for demonstration only.  You can get them from GitHub if you do not want to clone the entire project.
