### ISSUE TITLE
POV RAY demo code issues

### ISSUE THREAD

**Issue by Autonomousanz** [projectchrono/chrono#413]
The render_frames.pov generated after running the POV-ray demo file from the project chrono build has many issues to name a few:

    On running the demo_POST_povray from build chrono has Segmentation fault (core dumped) issue when running on ubuntu 20.4 with POV-Ray 3.7.0.8(g++ @ x86_64-pc-linux-gnu).
    The same demo running in ubuntu20.4 based docker image generated output files of stateXXXXX.pov files however while running the render_frames.pov, it is looking for bluewhite. file instead of bluewhite.png in textures folder
![Screenshot from 2022-07-16 17-31-18](https://user-images.githubusercontent.com/64002247/179373428-84a9962c-05d6-4026-94d4-e8bd505c991e.png)

After creating a bluewhite. dummy file in textures, that particular error was resolved just to throw a different error related to code
![Screenshot from 2022-07-16 17-51-22](https://user-images.githubusercontent.com/64002247/179373430-fe32f631-a70f-4048-b55a-892b8a910501.png)

**Comment by starwar9527** [comment]
I am facing the same issue

**Comment by rserban** [comment]
I pushed a fix to this issue.  It is available in the main branch of the repository.  Conda packages including this fix will be uploaded to anaconda.org in a few hours
