### ISSUE TITLE
[pychrono]SCMDeformable terrain with HMMWV vehicle

### ISSUE THREAD

**Issue by shunlibiye111** [projectchrono/chrono#425]
Hello everyone,I am attempting to set up a simulation with:
- hmmwv vehicle
- terrain with variable height from .bmp file
- deformable terrain with SCM model

The program runs normally,  the vehicle movement can be seen in the visualization interface and it can be seen that the terrain import is successful, but the  terrain with variable height from .bmp file cannot be visualized.

Any idea what may cause this and how to fix it?

Best Regards

**Comment by 20210401Yao** [comment]
nihao,woyeshi gang jiechu chrono zhege yinqin,nin keyi geige lianxi fangshi me,xiang he nin qingjiao yixie wenti.

**Comment by shunlibiye111** [comment]
> nihao,woyeshi gang jiechu chrono zhege yinqin,nin keyi geige lianxi fangshi me,xiang he nin qingjiao yixie wenti.

15650580615@163.com
