### ISSUE TITLE
Is there .py demo in pychrono as demo_VEH_TireTestRig.cpp , thanks!

### ISSUE THREAD

**Issue by hanhantuozi** [projectchrono/chrono#432]

**Comment by rserban** [comment]
No, we do not have the bandwidth to replicate all C++ demos in Python.  We only provide a set of illustrative examples. Having said that, it should be relatively straightforward to translate any of the C++ demos to a corresponding Python demo.  If you decide to create a demo_VEH_TireTestRig.py, please consider contributing it back through a pull request.
