### ISSUE TITLE
Compile chrono with future Spectra/KrylovSchurGEigsSolver.h (Modal module)

### ISSUE THREAD

**Issue by talregev** [projectchrono/chrono#437]
I trying to compile chrono with  modal  module that depend on spectra library.
I compile the chrono v8.0.0 with latest spectra: v1.0.1.
It ask me for `Spectra/KrylovSchurGEigsSolver.h`. 
I search on the repo and it coming from PR that didn't merge:
https://github.com/yixuan/spectra/pull/132

My question is how you compile your chrono with future file. 
Did you checkout this pr? 

Thanks in advanced.

**Comment by rserban** [comment]
Check out their `develop` branch.
That is indicated in **\*bold\*** on the Chrono installation instructions page for the Chrono::Modal module: https://api.projectchrono.org/module_modal_installation.html

**Comment by talregev** [comment]
@rserban `Spectra/KrylovSchurGEigsSolver.h` is not found on the develop branch. It found a PR. You should fix your documents.
