### ISSUE TITLE
 【windows】 Chrono::Vehicle cosimulation support requires MPI, but MPI not found

### ISSUE THREAD

**Issue by 1584319** [projectchrono/chrono#443]
Hi, recently, I try to install the projectchrono on my computer,
  I am appreciated if you can help me install the projectchrono.    

Searching for MPI...
Could NOT find MPI_C (missing: MPI_C_LIB_NAMES MPI_C_HEADER_DIR MPI_C_WORKS) 
Could NOT find MPI_CXX (missing: MPI_CXX_LIB_NAMES MPI_CXX_HEADER_DIR MPI_CXX_WORKS) 
Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND) 

Enable Irrlicht support
Add ChronoEngine_vehicle library
CMake Warning at src/chrono_vehicle/cosim/CMakeLists.txt:9 (message):
 Chrono::Vehicle cosimulation support requires MPI, but MPI not found
![image](https://user-images.githubusercontent.com/66416747/228844439-d64d2aa6-dcad-491c-9c45-18bd7008011a.png)

**Comment by rserban** [comment]
I am not quite sure what the question is.  The message you get is pretty clear: you do not have an MPI distribution installed on your machine and so the vehicle co-simulation framework, which relies on MPI, cannot be enabled. You can still install everything else in Chrono (including the vehicle module).  If you are interested in that particular functionality, then first install MPI (on Windows, which you appear to be using, I suggest either OpenMPI or Microsoft MPI -- both work fine).

**Comment by 1584319** [comment]
Thank you for your reply.
Recently, I had a new question about the   "Curiosity Mars Rover Model Class." 
1.Why are the same part obj files under two different folders (col, obj)?
![20230331093506](https://user-images.githubusercontent.com/66416747/229000693-1a5e7a4a-6a3c-486d-80f4-4f05ab77e3d9.png)
2.The connection relationship between two parts (such as a Revolute joint) can determine the connection position of two parts, but how do you know which parts are connected to each other?
![20230331093750](https://user-images.githubusercontent.com/66416747/229001031-e091a41f-17da-4839-aad4-97dd751e93a1.png)
For example, in the picture, how do you determine whether the two positions of serial number 1 and serial number 2 are connected, instead of two parts connecting at serial number 1 and serial number 3 or serial number 4

**Comment by rserban** [comment]
1. The two different directories with OBJ files are for visualization assets (obj/) and collision shapes (col/).  In general, these would be different, with the collision shapes being simplified versions of the corresponding visualization shapes (for efficiency considerations).  For the Curiosity model, we didn't get a chance to generate simpler collision meshes and so the two sets of files are the same.
2. You misunderstand how the model is constructed. Indeed, the parts you marked as (2, 3, 4) are in fact a single rigid body (see the mesh curiosity_B_L_arm.obj).  There is a single revolute joint which connects the body you marked with 1 with this other body.
I am not sure I understand your question about "how you know which two parts are connected by any given joint". You definitely do not try to infer that from a visualization of the mechanism, but rather from the physical description of the system. For a Chrono model such as this one, that means looking at the code where the model is defined (src/chrono_models/robot/curiosity/Curiosity.cpp)
