### ISSUE TITLE
How to use project chrono in QT? 

### ISSUE THREAD

**Issue by zanxueyan** [projectchrono/chrono#481]
Would you like to ask me how to use project chrono in QT? Can you provide a simple demo? I tried to complete QT using IRRLICHT, but didn't know how to replace it with prokect chrono. Look forward to your reply and advice.

**Comment by dariomangoni** [comment]
Hi zanxueyan,
please post questions to the [Google Forum](https://groups.google.com/g/projectchrono).
Some of us I think have some examples on embedding Chrono in QT, but this place is for tracking issue so we prefer to keep discussions on separate pages.

Thanks,
Dario
