### ISSUE TITLE
demo_VEH_WheeledJSON.cpp visual does not render in low frequency

### ISSUE THREAD

**Issue by hdy117** [projectchrono/chrono#491]
in file demo_VEH_WheeledJSON.cpp, vis render related function call should be invoked in a lower freqency. not within step_size

```c++
while (vis->Run()) {
      // Render scene
      vis->BeginScene();
      vis->Render();
      vis->EndScene();
```

**Comment by rserban** [comment]
This is just that: a demo.  In many of the Chrono demos, we elected to keep things as simple as possible to illustrate the important aspects.  In your code, of course, you are free to do as you please (and indeed, you may want to render at a lower frequency than the simulation one).
