### ISSUE TITLE
Bug? OpenGL does not work in combination with direct solvers

### ISSUE THREAD

**Issue by paulotto** [projectchrono/chrono#493]
Hello,

there seems to be a bug if OpenGL is used together with a direct solver like Pardiso MKL.

The following line seems to be the issue causing the simulation to crash:

https://github.com/projectchrono/chrono/blob/b32083f677353d1d2b2e36ace6a4063750e2444d/src/chrono_opengl/UI/ChOpenGLStats.cpp#L305

Best,
Paul

**Comment by rserban** [comment]
Paul - thanks for pointing this out.  Should be a simple fix. I'll look into it.
--Radu

**Comment by paulotto** [comment]
You're welcome.

Best,
Paul

**Comment by rserban** [comment]
Paul - I'll push a fix for this in a few minutes.  

Having said that, I was wondering why you use the Chrono::OpenGL run-time visualization in the first place.  Note that this module provides relatively limited capabilities as it is meant first and foremost for rendering results from large scale simulation (granular dynamics or SPH).  Hence the hardcoded assumption that one uses an iterative solver (left over from when this visualization module was working only with what is now Chrono::Multicore).

Anyway, everything should be working fine now, but, if possible, I recommend you use the Irrlicht, or even better the VSG options in Chrono.

**Comment by paulotto** [comment]
Thank you very much. I'll keep that in mind.
