### ISSUE TITLE
Update vendored version of Bullet to support C++11

### ISSUE THREAD

**Issue by andrewseidl** [projectchrono/chrono#51]
The version of Bullet included under [`src/collision/bullet`](https://github.com/projectchrono/chrono/tree/develop/src/collision/bullet) does not support C++11 due to issues in [`LinearMath/btSerializer.cpp`](https://github.com/bulletphysics/bullet3/blob/master/src/LinearMath/btSerializer.cpp), which have since been resolved upstream.

I see two courses of action that we can take in order to easily begin supporting C++11 in Chrono:

1. Fix the incompatibilities. This is easier and will minimize the amount of testing required. However, we will lose out on any bugfixes that may have been introduced over the last five years/1300 commits.

2. Update to a more recent version of Bullet. This will allow us to benefit from the last five years of Bullet's development, but could introduce new bugs. All validation tests will need to be rerun.

(There is also a third option in which the build system is told to build anything Bullet-related as C++03, but that only delays the issue and adds unnecessary complexity.)

If option 2 is chosen, I ask whoever performs the update to do the following:

* Continue to clearly mark lines where any changes were made.
* Make it obvious which version/commit of Bullet is being used.
* Include all relevant licenses.
* Preferably move the directory to `src/thirdparty` to make it obvious that the code is developed by a third party not associated with Chrono.
* Update `CMakeLists.txt` with all files (including headers). This is required for packaging and distribution.

-----------

I have tracked down Chrono's version to around Bullet [SHA 41314b5ebc](https://github.com/bulletphysics/bullet3/tree/41314b5ebc1bbdc34bd39406105e9e2b96f7a588). A diff of the real version of Bullet and Chrono's modified version is at: https://gist.github.com/andrewseidl/5ad3b592675465a4b569#file-bullet-diff

**Comment by tasora** [comment]
Hi Andrew,
    I made some modifications to the original Bullet, in fact. That's why I decided not to link it as an external lib, but I rather added most of its source in the Chrono GIT. 
    Now, if we want to update it to the more recent Bullet, we should redo those modifications. It is not that difficult, because, as you see in the diffs, I marked the changes with the "ALEX" comments. Also I added two or three additional btXXxxyyy.cpp / .h new files. 
Alessandro
