### ISSUE TITLE
Gravitational force by a planet/moon

### ISSUE THREAD

**Issue by wedesoft** [projectchrono/chrono#511]
Hi, I would like to use ProjectChrono for a space simulator.
How can I implement a force (i.e. gravitation) which depends on the position of a spacecraft relative to a planet's or moon's position in order to simulate takeoff, orbiting and landing of a spacecraft?
Kind regards
Jan

**Comment by wedesoft** [comment]
Also the position of the moon changes over time.

**Comment by rserban** [comment]
The most flexible way to do this is probably to use [ChLoadBodyBody](https://api.projectchrono.org/classchrono_1_1_ch_load_body_body.html).

Derive your own class from this and implement the virtual method `ComputeBodyBodyForceTorque`. You can access the two bodies with `GetBodyA` and `GetBodyB` to get their current positions and orientations.  

See [ChLoadBodyBodyBushingGeneric](https://github.com/projectchrono/chrono/blob/6f6bb4c6103de2764f38e9f27076818d17ab1fd3/src/chrono/physics/ChLoadsBody.cpp#L516) for an example.

**Comment by wedesoft** [comment]
Thanks for your response! Ok, will try. In the past I have successfully used Runge Kutta 4 integration to get stable orbits :)

**Comment by wedesoft** [comment]
Awesome, it seems to work as long as the time steps are small enough (source code: [chronoorbit.cc](https://github.com/wedesoft/chronotest/blob/c5112d209902bdf092eb3427e8862e0a5a7b2f54/chronoorbit.cc)).
I had to compile it with option `-DEIGEN_MAX_ALIGN_BYTES=32` because it was crashing otherwise.
![orbit](https://github.com/user-attachments/assets/e1bf0ddd-88ad-4d93-8a10-076a99f62b7c)

**Comment by wedesoft** [comment]
Thanks 👍
