### ISSUE TITLE
Non-smooth contacts incompatible with Runge Kutta integrator?

### ISSUE THREAD

**Issue by wedesoft** [projectchrono/chrono#512]
Hi,
I managed to get collisions working using NSC material and Euler Implicit Projected (source code: [stack.cc](https://github.com/wedesoft/chronotest/blob/dfcc46a14bf0caffcd6bad01f6b4116a6e37aafe/stack.cc)). However when I switch to the Runge Kutta 4 method, the collisions don't seem to work properly any more.

![falling stack](https://github.com/user-attachments/assets/3d1588c3-c924-4531-925a-fd258878f702)

Am I doing something wrong or is the NSC solver just incompatible with Runge Kutta integration?

**Comment by vacary** [comment]
For consistent RK application to nonsmooth systems, you can have a look to https://www.sciencedirect.com/science/article/pii/S1751570X24000062
