### ISSUE TITLE
Error reported when run Chrono::VEHICLE demo: "demo_VEH_SCMTerrain_WheeledVehicle"

### ISSUE THREAD

**Issue by ychen441** [projectchrono/chrono#514]
Lovely colleagues, 

I met the following error reported after I tried to run "_demo_VEH_SCMTerrain_WheeledVehicle_"  provided in "/bin" folder:

> Copyright (c) 2017 projectchrono.org
> Chrono version: 9.0.1
> demo_VEH_SCMTerrain_WheeledVehicle: /home/chen/chrono/src/chrono_thirdparty/HACDv2/dgVector.h:345: dgBigVector::dgBigVector(hacd::HaF64, hacd::HaF64, hacd::HaF64, hacd::HaF64): Assertion `((isfinite((*this)[0]) && !isnan((*this)[0])) && (isfinite((*this)[1]) && !isnan((*this)[1])) && (isfinite((*this)[2]) && !isnan((*this)[2])) && (isfinite((*this)[3]) && !isnan((*this)[3])))' failed.
> Aborted (core dumped)

Nothing weird happened when I ran SCM demos of rigid wheel and tracked vehicle.
Any solution to this issue? Thx :D 

Chen

**Comment by rserban** [comment]
Answered on user mailing list
