### ISSUE TITLE
ChFunctionSequence gives different results after latest updates

### ISSUE THREAD

**Issue by multibody** [projectchrono/chrono#529]
Hi,
I have just updated some code that was using pychrono 8 to pychrono 9 and noticed that the ChFunctionSequence gives different results now. This seems to be the case for negative x-values.

I attached an pychrono example with code for pychrono 8 and pychrono 9 to reproduce the problem. The problem consists of a simple linear ramp with the values x=[-1, 1] and y=[-1, 1]. In the negative x-area the results are different.

In pychrono 8 latest commit: c5b8194)  the function value at x=-0.5 is y=-0.5 (as expected).

In pychrono 9 latest commit: 882fec0)  the function value at x=-0.5 is y=0 (unexpected).

I hope this helps!

Christian

[chrono_8_9_function_sequence.txt](https://github.com/user-attachments/files/17598073/chrono_8_9_function_sequence.txt)

**Comment by rserban** [comment]
Fixed in commit 4b0cfe3f1

**Comment by multibody** [comment]
Thanks! :)
