### ISSUE TITLE
Simulate motion on gravel terrain

### ISSUE THREAD

**Issue by cyy227** [projectchrono/chrono#534]
Hello,I am currently working on a vehicle simulation in PyChrono, specifically for simulating movement on a gravel terrain. I found that the GranularTerrain class on your website is well-suited for this purpose, but I was unable to locate this class in the PyChrono Python API.

Could you please confirm if there is support for the GranularTerrain class in the Python version of Chrono? If not, could you suggest any alternative methods or classes within the Python environment that could simulate similar gravel terrain behavior for vehicle motion?

Thank you for your assistance!

**Comment by Huzaifg** [comment]
FYI - Project Chrono support is not provided here but in this [google group](https://groups.google.com/g/projectchrono)

To answer your question, 
Chrono Granular is not wrapped to PyChrono so you cannot use the GranularTerrain class in Python. There is no timeline at the moment to wrap this to Python.

Currently, PyChrono supports only one kind of deformable terrain - The SCM Terrain. [This is a demo for using it in Python ](https://github.com/projectchrono/chrono/blob/main/src/demos/python/vehicle/demo_VEH_DeformableSoil.py)
