### ISSUE TITLE
null mcontactable in ChParticlesClones

### ISSUE THREAD

**Issue by jcmadsen** [projectchrono/chrono#67]
line 196 of demo_postprocess.cpp throws an error, 

```
    mparticles->GetCollisionModel()->BuildModel();
```

Occurs during instantiation of ChParticlesClones, the ChModelBullet member mcontactable is set to 0 on line 181 of ChParticleClones.cpp:

```
    particle_collision_model = new ChModelBullet();
    particle_collision_model->SetContactable(0);
```

The result of calling GetPhysicItem() on the bullet collision model during BuildModel(), there is no mcontactable pointer to return the physics item.

The commented out check on line 84 of ChCModelBullet.cpp should be changed from

```
    // assert (GetPhysicsItem());
```

to 

```
assert(mcontactable);
```
for catching this error.

**Comment by tasora** [comment]
Fixed  with commit  389d6b2c69b05b742c268a878d4853deff37232b
