### ISSUE TITLE
Use `std::chrono` for ChProfiler

### ISSUE THREAD

**Issue by andrewseidl** [projectchrono/chrono#69]
C++11 introduced platform-independent timers and duration counters with `std::chrono`. Now that we're requiring C++11 support, new code should use `std::chrono` instead of platform-specific timers.

See, eg: http://en.cppreference.com/w/cpp/chrono/high_resolution_clock , http://en.cppreference.com/w/cpp/chrono/time_point , and http://en.cppreference.com/w/cpp/chrono/duration

Note that this may cause namespace issues in improper code that has `using namespace chrono;` or `using namespace std;`.

**Comment by tasora** [comment]
Ok, std::chrono used. There is only one small part of code that still uses the old timers  as the std::chrono cannot provide sub-millisecond precision (on Windows).
