### ISSUE TITLE
Compiling chrono generates an inordinate number of warning messages

### ISSUE THREAD

**Issue by DavidHammen** [projectchrono/chrono#77]
My bare minimum for a quality C++ software library is that it must compile clean with `-Wall` using either a GNU or LLVM compiler. The chrono code fails to meet this minimal standard.  With `-Wall`, I get several thousands of lines of warning messages. In fact, the chrono code does not compile clean even without `-Wall`.

**Comment by thepianoboy** [comment]
Fixed with commit db1ad88
