### ISSUE TITLE
MinGW 64-bit fails to build due to Bullet bug

### ISSUE THREAD

**Issue by dylanede** [projectchrono/chrono#80]
See https://github.com/bulletphysics/bullet3/issues/394 for discussion.

How this gets fixed in chrono depends on which minimum C++ standard version is supported. If C++11 is OK then `intptr_t` could be used to easily fix it.

**Comment by thepianoboy** [comment]
Fixed with commit 063e0d3

**Comment by dylanede** [comment]
Hmm, shouldn't that commit be merged before this is marked as fixed?

**Comment by thepianoboy** [comment]
Technically speaking, yes, but the commit is staged for merging just as soon as a bit of extra testing is completed. You can check out feature/remove_warnings if you want it sooner.
