### ISSUE TITLE
Python module compilation problem on linux

### ISSUE THREAD

**Issue by tapir** [projectchrono/chrono#93]
I'm on Arch linux 64 bit. I'm trying to compile from git.
I have python and irrlicht installed.
I've enabled python, irrlicht and vehicle with cmake and this what I get when trying to compile at 59%.

```
[ 59%] Linking CXX shared module _ChronoEngine_python_irrlicht.so
Error copying file "/home/tapir/Documents/chronoengine-git/src/chrono/build/lib/libChronoEngine_irrlicht.so" to "/usr/bin/DLLs/.".
make[2]: *** [src/chrono_python/CMakeFiles/_ChronoEngine_python_irrlicht.dir/build.make:108: src/chrono_python/_ChronoEngine_python_irrlicht.so] Error 1
make[2]: *** Deleting file 'src/chrono_python/_ChronoEngine_python_irrlicht.so'
make[1]: *** [CMakeFiles/Makefile2:1268: src/chrono_python/CMakeFiles/_ChronoEngine_python_irrlicht.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

If I leave out Irrlicht but keep python on then this is what I get:

```
[ 67%] Building CXX object src/chrono_python/CMakeFiles/_ChronoEngine_python_core.dir/__/__/python/ChModuleCorePYTHON_wrap.cxx.o
[ 67%] Linking CXX shared module /usr/bin/DLLs/_ChronoEngine_python_core.so
/usr/bin/ld: cannot open output file /usr/bin/DLLs/_ChronoEngine_python_core.so: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [src/chrono_python/CMakeFiles/_ChronoEngine_python_core.dir/build.make:105: /usr/bin/DLLs/_ChronoEngine_python_core.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:1228: src/chrono_python/CMakeFiles/_ChronoEngine_python_core.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

Disabling python and re-enabling irrlicht, compiles OK.

**Comment by tapir** [comment]
Any pointers how I can compile the python support?

**Comment by cekees** [comment]
@rserban I'm interested in some pointers for compiling with python support as well, especially under Python 2.7

**Comment by sanguinariojoe** [comment]
I fixed that replacing at src/chrono_python/CMakeLists.txt (Line 101) the following lines:

```
SET(CH_PYTHONDIR_PYD "${CH_PYTHONDIR}/DLLs")
SET(CH_PYTHONDIR_PY  "${CH_PYTHONDIR}/Lib")
```
by:

```
IF(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    SET(CH_PYTHONDIR_PYD "${PROJECT_BINARY_DIR}/python")
    SET(CH_PYTHONDIR_PY  "${PROJECT_BINARY_DIR}/python")
ELSE(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    SET(CH_PYTHONDIR_PYD "${CH_PYTHONDIR}/DLLs")
    SET(CH_PYTHONDIR_PY  "${CH_PYTHONDIR}/Lib")
ENDIF()
```

After that, you may compile without errors, and get all the python stuff at `python` subfolder (respect the place where you are compiling on)

That's a dirty trick, but good enough for the moment. Maybe @tapir would consider integrating it, or something like (MAC is not even considered bu the patch)...

**Comment by rserban** [comment]
I just pushed (to the `develop` branch) a rewrite of the CMakeLists.txt script for the Chrono::Python module (and other associated code fixes).   This should fix issues with configuring and building Python support, both on Windows and Linux platforms.  

I tested this on the following:
- Windows 10, Visual Studio 2013 Ultimate, SWIG 3.0.8, Python 3.6.0
- Windows 8, Visual Studio 2013 Pro, SWIG 3.0.8, Python 3.3
- Ubuntu 14.04 LTS, gcc 4.9.4, SWIG 3.0.10, Python 2.7.6
- CentOS Linux rel. 7.2.1511, SWIG 3.0.7, Python 3.6.0

Note that, after build (and optionally, installation), you must set the PYTHONPATH environment variable to point to the generated modules in either the BUILD or the INSTALL tree (during CMake configuration, the script will display the appropriate directories to be added to PYTHONPATH).  See the [installation guide](http://api.chrono.projectchrono.org/module_python_installation.html) for more details.

@cekees: As you can see, I also tested this with Python 2.7 and all seemed to work fine (without changes to any of the Python demo scripts -- which is a bit odd, but maybe it has to do with using a more recent SWIG version).  Please give it a try and let me know how it goes for you.
